// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Post_2.Models;

namespace Post_2.Migrations
{
    [DbContext(typeof(PostContext))]
    [Migration("20201112084147_views")]
    partial class views
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Post_2.Models.Post", b =>
                {
                    b.Property<int>("postID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("numberofviews")
                        .HasColumnType("int");

                    b.Property<string>("postContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("postLike")
                        .HasColumnType("int");

                    b.Property<string>("postTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timeUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("postID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Post_2.Models.comment", b =>
                {
                    b.Property<int>("commentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("commentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("postID")
                        .HasColumnType("int");

                    b.HasKey("commentID");

                    b.HasIndex("postID");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Post_2.Models.comment", b =>
                {
                    b.HasOne("Post_2.Models.Post", "post")
                        .WithMany("comments")
                        .HasForeignKey("postID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
