'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Newempreg
    Public Property Empid As Integer
    Public Property EmName As String
    Public Property Empemail As String
    Public Property Emplocation As String
    Public Property Empdesgnation As String

End Class
